// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RunScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunScript'](arg1, arg2, arg3);
}
