// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGroups():Promise<Array<main.GroupData>>;

export function PickFile():Promise<string>;

export function PickFolder():Promise<string>;

export function RunScript(arg1:number,arg2:number,arg3:Array<string>):Promise<main.RunResult>;
